dist: trusty
language: go

go:
  - 1.11.x
  
addons:
  sonarcloud:
    organization: "mikspec-github" # the key of the org you chose at step #3
      
script:
  - go test -coverprofile=coverage.out ./...
  - sonar-scanner
