dist: trusty
language: go

go:
  - 1.11.x
  
before_install:
  - go get github.com/mattn/goveralls

addons:
  sonarcloud:
    organization: "mikspec-github" # the key of the org you chose at step #3
      
script:
  - go test -coverprofile=coverage.out ./...
  - $HOME/gopath/bin/goveralls -v -service=travis-ci
  - sonar-scanner
